from playwright.sync_api import Page, expect, sync_playwright
import time
from datetime import datetime
from datetime import datetime
import string
import random

def login_scm(page: Page):        
    page.goto("https://scm.tokoparts.mitija-dev.net/")
    page.locator(f"#username").fill("Admin")
    time.sleep(2)
    page.locator(f"#password").fill("bukan_raHasi4")
    time.sleep(2)
    page.locator('[class="btn btn-primary-red btn-block"]').click()
    time.sleep(2)
    expect(page.locator("h1")).to_have_text("Welcome")
    time.sleep(2)
    page.locator("h1").text_content()
    time.sleep(2)

def login_frontline(page: Page):
    page.goto("https://tokoparts.mitija-dev.net/login")
    time.sleep(2)
    page.locator("#txtBuyerLoginEmailPhone").fill("ptperusahaanuat1@gmail.com")
    time.sleep(1)
    page.locator("#txtBuyerLoginPassword").fill("123456")
    time.sleep(1)
    page.locator('[class="btn btn-login"]').click()
    time.sleep(3)

def screenshoot(page: Page, test_context, filename: str = "screenshot"):
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    screenshot_path = f"reports/screenshots/manual_{timestamp}_{filename}.png"
    original_viewport = page.viewport_size
    try:
        page.set_viewport_size({"width": 1521, "height": 1000})
        page.wait_for_timeout(500)  # beri waktu browser layout
        # Screenshot persis 1521x1000
        page.screenshot(path=screenshot_path, full_page=False)
        # Simpan ke test_context
        test_context["record_screenshot"](screenshot_path)
    finally:
        if original_viewport:
            page.set_viewport_size(original_viewport)


def Create_Lala_Reguler(page: Page):
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    #Verify Form Delivery Service Open
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('input[aria-controls="select2-beneficiary_name-results"]').fill("Lalamove")
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Reguler")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Reguler")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    discount = page.locator(f"#delivery_fee_discount")
    discount.fill("100")
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    expect(page.locator('.swal-title')).to_have_text("Berhasil!")
    expect(page.locator('.swal-text')).to_have_text("Data berhasil disimpan")
    time.sleep(1)
    page.press('body', "Enter")

def Create_Lala_Instant(page: Page):
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    #Verify Form Delivery Service Open
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('input[aria-controls="select2-beneficiary_name-results"]').fill("Lalamove")
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    discount = page.locator(f"#delivery_fee_discount")
    discount.fill("100")
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    expect(page.locator('.swal-title')).to_have_text("Berhasil!")
    expect(page.locator('.swal-text')).to_have_text("Data berhasil disimpan")
    time.sleep(1)
    page.press('body', "Enter")

def Create_Lala_Sameday(page: Page):
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    #Verify Form Delivery Service Open
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('input[aria-controls="select2-beneficiary_name-results"]').fill("Lalamove")
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Sameday")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Sameday")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    discount = page.locator(f"#delivery_fee_discount")
    discount.fill("100")
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    expect(page.locator('.swal-title')).to_have_text("Berhasil!")
    expect(page.locator('.swal-text')).to_have_text("Data berhasil disimpan")
    time.sleep(1)    
    page.press('body', "Enter")

def Create_Other_Reguler(page: Page):
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    #Verify Form Delivery Service Open
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('input[aria-controls="select2-beneficiary_name-results"]').fill("JKT Express")
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("JKT Express")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Reguler")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Reguler")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    discount = page.locator(f"#delivery_fee_discount")
    discount.fill("100")
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    expect(page.locator('.swal-title')).to_have_text("Berhasil!")
    expect(page.locator('.swal-text')).to_have_text("Data berhasil disimpan")
    time.sleep(1)
    page.press('body', "Enter")

def Create_Other_SameDay(page: Page):
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    #Verify Form Delivery Service Open
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('input[aria-controls="select2-beneficiary_name-results"]').fill("JKT Express")
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("JKT Express")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Sameday")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Sameday")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    discount = page.locator(f"#delivery_fee_discount")
    discount.fill("100")
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    expect(page.locator('.swal-title')).to_have_text("Berhasil!")
    expect(page.locator('.swal-text')).to_have_text("Data berhasil disimpan")
    time.sleep(1)
    page.press('body', "Enter")    

def Create_Other_Instant(page: Page):
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    #Verify Form Delivery Service Open
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('input[aria-controls="select2-beneficiary_name-results"]').fill("JKT Express")
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("JKT Express")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    discount = page.locator(f"#delivery_fee_discount")
    discount.fill("100")
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    expect(page.locator('.swal-title')).to_have_text("Berhasil!")
    expect(page.locator('.swal-text')).to_have_text("Data berhasil disimpan")
    time.sleep(1)
    page.press('body', "Enter")        

def Search_Lala_Reguler(page: Page):
    page.goto("https://scm.tokoparts.mitija-dev.net/setting/delivery-service")
    time.sleep(1)
    page.locator('[href="#advsSearch"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[1]/div/span/span[1]/span/ul/li/input').fill("Lalamove")
    page.locator('//*[@id="frmAdvance"]/div[1]/div/span/span[1]/span/ul/li/input').press("Enter")
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[2]/div/span/span[1]/span/ul/li/input').fill('REGULER')
    page.locator('//*[@id="frmAdvance"]/div[2]/div/span/span[1]/span/ul/li/input').press('Enter')
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[4]/div/div/div/span/span[1]/span/ul/li/input').fill('ACTIVE')
    page.locator('//*[@id="frmAdvance"]/div[4]/div/div/div/span/span[1]/span/ul/li/input').press('Enter')
    time.sleep
    page.locator('#btn_adv_search').click()

def Search_Lala_Instant(page: Page):
    page.goto("https://scm.tokoparts.mitija-dev.net/setting/delivery-service")
    time.sleep(1)
    page.locator('[href="#advsSearch"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[1]/div/span/span[1]/span/ul/li/input').fill("Lalamove")
    page.locator('//*[@id="frmAdvance"]/div[1]/div/span/span[1]/span/ul/li/input').press("Enter")
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[2]/div/span/span[1]/span/ul/li/input').fill('INSTANT')
    page.locator('//*[@id="frmAdvance"]/div[2]/div/span/span[1]/span/ul/li/input').press('Enter')
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[4]/div/div/div/span/span[1]/span/ul/li/input').fill('ACTIVE')
    page.locator('//*[@id="frmAdvance"]/div[4]/div/div/div/span/span[1]/span/ul/li/input').press('Enter')
    time.sleep
    page.locator('#btn_adv_search').click()

def Search_Lala_Sameday(page: Page):
    page.goto("https://scm.tokoparts.mitija-dev.net/setting/delivery-service")
    time.sleep(1)
    page.locator('[href="#advsSearch"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[1]/div/span/span[1]/span/ul/li/input').fill("Lalamove")
    page.locator('//*[@id="frmAdvance"]/div[1]/div/span/span[1]/span/ul/li/input').press("Enter")
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[2]/div/span/span[1]/span/ul/li/input').fill('SAMEDAY')
    page.locator('//*[@id="frmAdvance"]/div[2]/div/span/span[1]/span/ul/li/input').press('Enter')
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[4]/div/div/div/span/span[1]/span/ul/li/input').fill('ACTIVE')
    page.locator('//*[@id="frmAdvance"]/div[4]/div/div/div/span/span[1]/span/ul/li/input').press('Enter')
    time.sleep
    page.locator('#btn_adv_search').click()

def Search_Other_Reguler(page: Page):
    page.goto("https://scm.tokoparts.mitija-dev.net/setting/delivery-service")
    time.sleep(1)
    page.locator('[href="#advsSearch"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[1]/div/span/span[1]/span/ul/li/input').fill("JKT Express")
    page.locator('//*[@id="frmAdvance"]/div[1]/div/span/span[1]/span/ul/li/input').press("Enter")
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[2]/div/span/span[1]/span/ul/li/input').fill('REGULER')
    page.locator('//*[@id="frmAdvance"]/div[2]/div/span/span[1]/span/ul/li/input').press('Enter')
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[4]/div/div/div/span/span[1]/span/ul/li/input').fill('ACTIVE')
    page.locator('//*[@id="frmAdvance"]/div[4]/div/div/div/span/span[1]/span/ul/li/input').press('Enter')
    time.sleep
    page.locator('#btn_adv_search').click()

def Search_Other_SameDay(page: Page):
    page.goto("https://scm.tokoparts.mitija-dev.net/setting/delivery-service")
    time.sleep(1)
    page.locator('[href="#advsSearch"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[1]/div/span/span[1]/span/ul/li/input').fill("JKT Express")
    page.locator('//*[@id="frmAdvance"]/div[1]/div/span/span[1]/span/ul/li/input').press("Enter")
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[2]/div/span/span[1]/span/ul/li/input').fill('SAMEDAY')
    page.locator('//*[@id="frmAdvance"]/div[2]/div/span/span[1]/span/ul/li/input').press('Enter')
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[4]/div/div/div/span/span[1]/span/ul/li/input').fill('ACTIVE')
    page.locator('//*[@id="frmAdvance"]/div[4]/div/div/div/span/span[1]/span/ul/li/input').press('Enter')
    time.sleep
    page.locator('#btn_adv_search').click()

def Search_Other_Instant(page: Page):
    page.goto("https://scm.tokoparts.mitija-dev.net/setting/delivery-service")
    time.sleep(1)
    page.locator('[href="#advsSearch"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[1]/div/span/span[1]/span/ul/li/input').fill("JKT Express")
    page.locator('//*[@id="frmAdvance"]/div[1]/div/span/span[1]/span/ul/li/input').press("Enter")
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[2]/div/span/span[1]/span/ul/li/input').fill('INSTANT')
    page.locator('//*[@id="frmAdvance"]/div[2]/div/span/span[1]/span/ul/li/input').press('Enter')
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[4]/div/div/div/span/span[1]/span/ul/li/input').fill('ACTIVE')
    page.locator('//*[@id="frmAdvance"]/div[4]/div/div/div/span/span[1]/span/ul/li/input').press('Enter')
    time.sleep
    page.locator('#btn_adv_search').click()

def Add_Product_To_Cart(page: Page):
    page.locator('.img-cart').click()
    time.sleep(1)
    page.goto('[href="https://tokoparts.mitija-dev.net/buyers/view-cart"]')
    page.locator('.checkout-style-3').click()
    page.press('body', "Tab") 
    page.press('body', "Enter")
    time.sleep(1) 
    page.locator('#categoryButton').click()
    time.sleep(1)
    page.goto('https://tokoparts.mitija-dev.net/part-list-by-category?category=4')
    time.sleep(1)
    page.goto('https://tokoparts.mitija-dev.net/part-detail/23311')
    time.sleep(1)
    page.evaluate('addCart(23311)')
    time.sleep(1)
    page.press('body', "Enter")
    time.sleep(1)
    page.locator('.img-cart').click()
    time.sleep(1)
    page.goto('[href="https://tokoparts.mitija-dev.net/buyers/view-cart"]')
    page.locator('#categoryButton').click()
    page.locator('.checkout-style-3').click()
    page.press('body', "Enter")
    

def Add_Product_To_Cart_With_COD(page: Page):
    page.goto('https://tokoparts.mitija-dev.net/buyers/view-cart')
    time.sleep(1)
    page.locator('.checkout-style-3').click()
    page.press('body', "Tab") 
    page.press('body', "Enter")
    time.sleep(1) 
    page.locator('#categoryButton').click()
    time.sleep(1)
    page.goto('https://tokoparts.mitija-dev.net/part-list-by-category?category=4')
    time.sleep(1)
    page.goto('https://tokoparts.mitija-dev.net/part-detail/23311')
    time.sleep(1)
    page.evaluate('addCart(23311)')
    time.sleep(1)
    page.goto('https://tokoparts.mitija-dev.net/buyers/view-cart')
    page.locator('#is_cod').click()
    page.locator('.checkout-style-3').hover()

    time.sleep(2)   
    

 