from playwright.sync_api import Playwright, Page, expect, sync_playwright
import time
from login_function_tokoparts import login_scm
import string
import random
import os
from report_utils import generate_pdf_report, generate_consolidated_pdf_report

def test_case_1_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    #Verify Form Delivery Service Open
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('[for="api_integration"]')).to_have_text("API Integration")
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)
    expect(page.locator('[for="beneficiary_name"]')).to_have_text("3 PL Name")
    expect(page.locator(f'#select2-beneficiary_name-container')).to_be_visible()

    expect(page.locator('[for="entity"]')).to_have_text("Branch Allocation")
    expect(page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button')).to_be_visible()

    expect(page.locator('//*[@id="frmData"]/div[1]/div[4]/div/div')).to_have_text("Select All Branches")

    expect(page.locator('//*[@id="frmData"]/div[1]/div[5]/label')).to_have_text("Service Type (3PL)")
    expect(page.locator('#select2-service_type_common-container')).to_be_visible()

    expect(page.locator('//*[@id="frmData"]/div[1]/div[6]/label')).to_have_text("Service Type (SCO)")
    expect(page.locator('#select2-service_type_sco-container')).to_be_visible()
    
    expect(page.locator('[for="vehicle_type"]')).to_have_text("Vehicle Type *")
    expect(page.locator('#select2-vehicle_type-container')).to_be_visible()

    expect(page.locator('//*[@id="frmData"]/div[1]/div[9]/label')).to_have_text("Shipping Name")
    expect(page.locator('#shipping_name_common')).to_be_visible()

    expect(page.locator('//*[@id="pricing-form"]/div[1]/label')).to_have_text("Base Delivery Price")
    expect(page.locator('#delivery_fee_ori')).to_be_visible()

    expect(page.locator('//*[@id="pricing-form"]/div[2]/label')).to_have_text('Delivery Discount (SCO)')
    expect(page.locator('#delivery_fee_discount')).to_be_visible()

    expect(page.locator('//*[@id="pricing-form"]/div[3]/label')).to_have_text("Delivery Price")
    expect(page.locator('#delivery_fee')).to_be_visible()

    expect(page.locator('//*[@id="frmData"]/div[1]/div[12]/label')).to_have_text("Shipping Status")
    expect(page.locator('#status')).to_be_visible()

    expect(page.locator('//*[@id="frmData"]/div[1]/div[13]/label')).to_have_text("Cash on Delivery")
    expect(page.locator('#is_cod')).to_be_visible()
    time.sleep(2)


def test_case_2_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    #Verify Form Delivery Service Open
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('input[aria-controls="select2-beneficiary_name-results"]').fill("Lalamove")
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    sco_service_value = page.locator("#select2-service_type_sco-container").text_content().upper()
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    discount = page.locator(f"#delivery_fee_discount")
    discount.fill("100")
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    expect(page.locator('.swal-title')).to_have_text("Berhasil!")
    expect(page.locator('.swal-text')).to_have_text("Data berhasil disimpan")
    time.sleep(1)
    page.locator('[class="swal-button swal-button--confirm"]').click()
    time.sleep(2)
    #VerifyAfterCreateDeliveryConfig
    page.locator('[href="#advsSearch"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[3]/div/span/span[1]/span/ul/li/input').fill(random_text)
    time.sleep(1)
    page.locator('[class="select2-results__options"]').click()
    time.sleep(1)
    page.locator('#btn_adv_search').click()
    time.sleep(1)
    expect(page.locator("td").nth(2)).to_have_text("Detail")
    time.sleep(1)
    expect(page.locator("td").nth(3)).to_have_text(sco_service_value)
    time.sleep(1)
    expect(page.locator("td").nth(4)).to_have_text(random_text)
    time.sleep(1)
    expect(page.locator("td").nth(6)).to_have_text("ACTIVE")
    time.sleep(1)
    expect(page.locator("td").nth(7)).to_have_text("Edit")
    time.sleep(1)
    #VerifyConditionEdit
    page.locator('[class="btn btn-sm btn-default btn-black pull-right ml-1 btn-edit"]').click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(5)
    expect(page.locator('#select2-beneficiary_name-container')).to_be_disabled()
    time.sleep(1)
    expect(page.locator('#select2-service_type_common-container')).to_be_disabled()
    time.sleep(1)
    expect(page.locator('#select2-service_type_sco-container')).to_be_disabled()
    time.sleep(1)
    expect(page.locator('#delivery_fee_ori')).to_be_disabled()
    time.sleep(1)
    from report_utils import generate_pdf_report
    generate_pdf_report(request.node)  # Kirim test item ke PDF generator
    print("PDF report triggered!")  # Debug line

def test_case_3_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    #Verify Form Delivery Service Open
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('input[aria-controls="select2-beneficiary_name-results"]').fill("Lalamove")
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    sco_service_value = page.locator("#select2-service_type_sco-container").text_content().upper()
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    basefee = page.locator(f"#delivery_fee_ori")
    basefee.fill("1000")
    discount = page.locator(f"#delivery_fee_discount")
    discount.fill("100")
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    expect(page.locator('.swal-title')).to_have_text("Berhasil!")
    expect(page.locator('.swal-text')).to_have_text("Data berhasil disimpan")
    time.sleep(1)
    page.locator('[class="swal-button swal-button--confirm"]').click()
    time.sleep(2)
    #VerifyAfterCreateDeliveryConfig
    page.locator('[href="#advsSearch"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmAdvance"]/div[3]/div/span/span[1]/span/ul/li/input').fill(random_text)
    time.sleep(1)
    page.locator('[class="select2-results__options"]').click()
    time.sleep(1)
    page.locator('#btn_adv_search').click()
    time.sleep(1)
    expect(page.locator("td").nth(2)).to_have_text("Detail")
    time.sleep(1)
    expect(page.locator("td").nth(3)).to_have_text(sco_service_value)
    time.sleep(1)
    expect(page.locator("td").nth(4)).to_have_text(random_text)
    time.sleep(1)
    expect(page.locator("td").nth(6)).to_have_text("ACTIVE")
    time.sleep(1)
    expect(page.locator("td").nth(7)).to_have_text("Edit")
    time.sleep(1)
    #VerifyConditionEdit
    page.locator('[class="btn btn-sm btn-default btn-black pull-right ml-1 btn-edit"]').click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(5)
    expect(page.locator('#select2-beneficiary_name-container')).to_be_disabled()
    time.sleep(1)
    expect(page.locator('#select2-service_type_common-container')).to_be_disabled()
    time.sleep(1)
    expect(page.locator('#select2-service_type_sco-container')).to_be_disabled()
    time.sleep(1)
    expect(page.locator('#delivery_fee_ori')).to_be_enabled   
    time.sleep(1)    

def test_case_4_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)    
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    #Verify Error Message
    expect(page.locator('.swal-title')).to_have_text("Error")
    expect(page.locator('.swal-text')).to_have_text("Entity wajib dipilih minimal 1")
    time.sleep(1)

def test_case_5_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)    
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Select Service Type")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    #Verify Error Message
    expect(page.locator('//*[@id="alertData"]/div/div[2]/div')).to_have_text('The "Service Type (3PL)" field is required.')
    time.sleep(1)

def test_case_6_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Select Service Type")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    time.sleep(1)
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    #Verify Error Message
    expect(page.locator('//*[@id="alertData"]/div/div[2]/div')).to_have_text('The "Service Type (SCO)" field is required.')
    time.sleep(1)

def test_case_7_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)    
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    time.sleep(1)
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    #Verify Error Message
    expect(page.locator('//*[@id="alertData"]/div/div[2]/div')).to_have_text('The vehicle type field is required.')
    time.sleep(1)

def test_case_8_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)    
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    time.sleep(1)
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    #Verify Error Message
    expect(page.locator('//*[@id="alertData"]/div/div[2]/div')).to_have_text('The "Shipping Name" field is required.')
    time.sleep(1)

def test_case_9_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)    
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    #Verify Error Message
    expect(page.locator('//*[@id="alertData"]/div/div[2]/div')).to_have_text('The status field is required.')
    time.sleep(1)

def test_case_10_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)    
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('.bootstrap-switch-label').click()
    time.sleep(2)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    sco_service_value = page.locator("#select2-service_type_sco-container").text_content().upper()
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    price = page.locator(f"#delivery_fee_ori")
    price.fill("10000")
    discount = page.locator(f"#delivery_fee_discount")
    discount.fill("100")
    value_discount = int(discount.input_value())
    time.sleep(1)
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    expect(page.locator('//*[@id="alertData"]/div/div[2]/div')).to_have_text('The is cod field is required.')
    time.sleep(1)

def test_case_11_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)    
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    page.locator('#delivery_fee_ori').fill('10000')
    time.sleep(1)
    page.locator('#delivery_fee_discount').fill('100')
    time.sleep
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    #Verify Error Message
    expect(page.locator('.swal-title')).to_have_text("Error")
    expect(page.locator('.swal-text')).to_have_text("Entity wajib dipilih minimal 1")
    time.sleep(1)

def test_case_12_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)    
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Select Service Type")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    page.locator('#delivery_fee_ori').fill('10000')
    time.sleep(1)
    page.locator('#delivery_fee_discount').fill('100')
    time.sleep
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    #Verify Error Message
    expect(page.locator('//*[@id="alertData"]/div/div[2]/div')).to_have_text('The "Service Type (3PL)" field is required.')
    time.sleep(1)

def test_case_13_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Select Service Type")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    page.locator('#delivery_fee_ori').fill('10000')
    time.sleep(1)
    page.locator('#delivery_fee_discount').fill('100')
    time.sleep(1)
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    #Verify Error Message
    expect(page.locator('//*[@id="alertData"]/div/div[2]/div')).to_have_text('The "Service Type (SCO)" field is required.')
    time.sleep(1)

def test_case_14_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)    
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    page.locator('#delivery_fee_ori').fill('10000')
    time.sleep(1)
    page.locator('#delivery_fee_discount').fill('100')
    time.sleep(1)
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    #Verify Error Message
    expect(page.locator('//*[@id="alertData"]/div/div[2]/div')).to_have_text('The vehicle type field is required.')
    time.sleep(1)

def test_case_15_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)    
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    page.locator('#delivery_fee_ori').fill('10000')
    time.sleep(1)
    page.locator('#delivery_fee_discount').fill('100')
    time.sleep(1)
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    #Verify Error Message
    expect(page.locator('//*[@id="alertData"]/div/div[2]/div')).to_have_text('The "Shipping Name" field is required.')
    time.sleep(1)

def test_case_16_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)    
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    page.locator('#delivery_fee_ori').fill('10000')
    time.sleep(1)
    page.locator('#delivery_fee_discount').fill('100')
    time.sleep(1)
    page.locator("#is_cod").select_option(value="1")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    #Verify Error Message
    expect(page.locator('//*[@id="alertData"]/div/div[2]/div')).to_have_text('The status field is required.')
    time.sleep(1)

def test_case_17_UserStory1(page: Page, request):
    login_scm(page)
    page.locator('[src="/img/admin/truck.png"]').click()
    time.sleep(1)
    page.locator('[href="https://scm.tokoparts.mitija-dev.net/setting/delivery-service"]').click()
    time.sleep(1)
    expect(page.locator('[class="sellers-list"]')).to_have_text("Delivery Service List")
    time.sleep(1)
    page.locator(f"#btnAdd").click()
    time.sleep(1)
    expect(page.locator('//*[@id="dlgData"]/div/div/div/h4')).to_have_text("Form Delivery Service")
    time.sleep(1)
    #Verify Api Integrartion is off
    expect(page.locator('//*[@id="frmData"]/div[1]/div[2]/div/div/div/span[3]')).to_have_text("OFF")
    time.sleep(1)    
    page.locator(f"#select2-beneficiary_name-container").click()
    time.sleep(1)
    page.locator('#select2-beneficiary_name-results li:has-text("Lalamove")').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator('[title="Tokoparts Branch - Jakarta"]').click()
    page.locator('[title="Tokoparts Branch - Medan"]').click()
    page.locator('[title="Tokoparts Branch - Bandung"]').click()
    time.sleep(1)
    page.locator('//*[@id="frmData"]/div[1]/div[4]/div/span/span/div/button').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_common-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator(f"#select2-service_type_sco-container").click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Instant")').click()
    time.sleep(1)
    page.locator('[title="Select Vehicle Type"]').click()
    time.sleep(1)
    page.locator('.select2-results__option:has-text("Motor")').click()
    time.sleep(1)
    characters = string.ascii_letters + string.digits
    random_text = ''.join(random.choice(characters) for i in range(10))
    page.locator(f"#shipping_name_common").fill(random_text)
    time.sleep(1)
    price = page.locator(f"#delivery_fee_ori")
    price.fill("10000")
    discount = page.locator(f"#delivery_fee_discount")
    discount.fill("100")
    time.sleep(1)
    page.locator("#status").select_option(value="ACTIVE")
    time.sleep(1)
    page.locator(".phpdebugbar-close-btn").click()
    time.sleep(1)
    page.get_by_role("button", name="Save").click()
    time.sleep(1)
    expect(page.locator('//*[@id="alertData"]/div/div[2]/div')).to_have_text('The is cod field is required.')
    time.sleep(1)

if __name__ == '__main__':
    with sync_playwright() as p:
        browser = p.chromium.launch(channel="chrome", headless=False)
        page = browser.new_page() 